package pl.kondziet.streamsamples.model.enums;

public enum PostCategory {
    FILTERING, MAPPING, SORTING, AGGREGATION, MATCHING, SEARCHING, LIMITING, SKIPPING, DISTINCT, REDUCING, COLLECTING, ITERATING, GENERATING, COMBINING, PARALLEL_PROCESSING
}
